Create chore of project
meilisearch/gatsby-plugin-meilisearch pull request #17
Opened 2021-06-29 08:20 UTC by mdubus

Closes #2

2021-06-29 10:53 UTC, bidoubiwa requested changes
~is `index.js` necessary?~

2021-06-29 10:53 UTC, bidoubiwa commented on package.json
> +  "description": "A plugin to index your Gatsby content to MeiliSearch based on graphQL queries",
```suggestion
  "description": "Gatsby plugin to index your content to MeiliSearch based on queries",
```

No need to specify graphql, and reworded plugin presentation based on: 

<img width="915" alt="Screenshot 2021-06-29 at 12 40 24" src="https://user-images.githubusercontent.com/33010418/123783987-41e49600-d8d7-11eb-9b44-a09f25d7b7fb.png">

2021-06-29 10:53 UTC, bidoubiwa commented on package.json
> +    "lint": "eslint --ext .js ."
```suggestion
    "lint": "eslint --ext .js .",
    "lint:fix": "eslint --ext .js . --fix"
    
```

Add fixing script (could you confirm it works?)

2021-06-29 10:53 UTC, bidoubiwa commented on .github/dependabot.yml
> +      - dependencies
prettier and eslint should be added to ignore list

2021-06-29 10:53 UTC, bidoubiwa commented on .eslintrc.json
> +}
Should prettier be added to the rules to avoid conflict and to both extend and rules to be applied?

For example the [strapi .eslint](https://github.com/meilisearch/strapi-plugin-meilisearch/blob/main/.eslintrc.js).

2021-06-29 11:05 UTC, bidoubiwa commented
Could you add the following  to the readme ?


Bors 
```html
 <a href="https://app.bors.tech/repositories/28908"><img src="https://bors.tech/images/badge_small.svg" alt="Bors enabled"></a>
```

Tests (please update with github action from this repo)

```html
<a href="https://github.com/meilisearch/meilisearch-js/actions"><img src="https://github.com/meilisearch/meilisearch-js/workflows/Tests/badge.svg" alt="Tests"></a>
```

2021-06-29 11:28 UTC, mdubus commented
> ~is `index.js` necessary?~

Nope, but I added it so that eslint doesn't fail (because it found 0 files to lint) and so that the CI doesn't either :D

2021-06-29 12:45 UTC, mdubus commented on package.json
> +    "lint": "eslint --ext .js ."
It does with the proper plugins. Just added it to an other commit 😉

2021-06-29 12:46 UTC, mdubus commented on .github/dependabot.yml
> +      - dependencies
Why ? Don't we want the updates for these 2 plugins ?

2021-06-29 12:52 UTC, mdubus commented
> Could you add the following badges to the readme ?
> 
> Bors
> 
> ```
>  <a href="https://app.bors.tech/repositories/28908"><img src="https://bors.tech/images/badge_small.svg" alt="Bors enabled"></a>
> ```
> 
> Tests (please update with github action from this repo)
> 
> ```
> <a href="https://github.com/meilisearch/meilisearch-js/actions"><img src="https://github.com/meilisearch/meilisearch-js/workflows/Tests/badge.svg" alt="Tests"></a>
> ```

Done, thanks a lot 🙏

2021-06-29 12:57 UTC, curquiza commented on README.md
> +  <a href="https://app.bors.tech/repositories/28908"><img src="https://bors.tech/images/badge_small.svg" alt="Bors enabled"></a>
```suggestion
  <a href="https://app.bors.tech/repositories/34942"><img src="https://bors.tech/images/badge_small.svg" alt="Bors enabled"></a>
```

2021-06-29 12:57 UTC, curquiza reviewed
I've added bors to this repo: @mdubus, @bidoubiwa and @curquiza can `bors merge`
Every meili people can `bors try`

2021-06-29 12:59 UTC, curquiza commented
bors try

2021-06-29 12:59 UTC, mdubus commented on README.md
> +  <a href="https://app.bors.tech/repositories/28908"><img src="https://bors.tech/images/badge_small.svg" alt="Bors enabled"></a>
Oupsie 🙊 , thanks

2021-06-29 15:11 UTC, mdubus commented on .eslintrc.json
> +}
Done

2021-06-29 15:13 UTC, mdubus commented on .github/dependabot.yml
> +      - dependencies
Done 😀

2021-07-01 09:48 UTC, bidoubiwa approved these changes
LGTM 🔥

2021-07-01 12:06 UTC, mdubus commented
bors merge

2021-07-01 12:07 UTC, merged