Add playground
meilisearch/gatsby-plugin-meilisearch pull request #20
Opened 2021-07-05 14:56 UTC by mdubus

Closes #3

2021-07-06 17:40 UTC, bidoubiwa requested changes
🔥

2021-07-06 17:40 UTC, bidoubiwa commented on .prettierrc
> +}
```suggestion
```

rules are conflicting with eslintrc, to avoid this, they should only be added in `.eslintrc` here: 

```
   "prettier/prettier": [
      "error",
      {
        "quoteProps": "consistent",
        "semi": false,
        "arrowParens": "avoid",
        "singleQuote": true
// here
      }
    ]
```

2021-07-06 17:40 UTC, bidoubiwa commented on README.md
> +Note that you might need to change the host and the API Key of your MeiliSearch client [here](./playground/src/pages/index.js).
Since it is information that will help users play with the plugin and not information on how to install or use the plugin, it should be in `CONTRIBUTING.md`

2021-07-06 17:40 UTC, bidoubiwa commented on package.json
> +    "playground:serve": "yarn --cwd ./playground serve"
```suggestion
    "playground:dev": "yarn --cwd ./playground && yarn --cwd ./playground develop",
    "playground:build": "yarn --cwd ./playground && yarn --cwd ./playground build",
    "playground:serve": "yarn --cwd ./playground && yarn --cwd ./playground serve"
```

the first part `yarn --cwd ./playground` is used to install the packages in case the user forgot to `yarn install` in the repository. Because it can happen in all three cases it is best to keep them everywhere

2021-07-06 17:40 UTC, bidoubiwa commented on playground/README.md
> +A simple Gatsby blog to test the indexation of its articles inside MeiliSearch
Because it is markdown I cannot make the suggestion in markdown :( Lets add a bit more explanation to the playground readme: 

# Gatsby Playground

## Project setup
```
yarn install
```

### Compiles and hot-reloads for development
```
yarn serve
```

### Compiles and minifies for production
```
yarn build
```

2021-07-07 15:48 UTC, bidoubiwa requested changes

2021-07-07 15:48 UTC, bidoubiwa commented on .prettierrc
> +
I think the file may be deleted

2021-07-08 06:36 UTC, mdubus commented on .prettierrc
> +
You're absolutely right 🤣 It's done !

2021-07-08 10:07 UTC, bidoubiwa approved these changes
bors merge

2021-07-08 10:08 UTC, merged