Bind plugin with playground
meilisearch/gatsby-plugin-meilisearch pull request #21
Opened 2021-07-13 09:24 UTC by mdubus

## What's inside this PR ? 

Binding of the plugin with the playground: 
- change of the plugin entry point
- addition of the plugin in the `gatsby-config` file

I also added a test to prove that the binding is made correctly. This will be removed later in the development process.

## How to test ? 

On build, the plugin will programatically create a `Test page` that doesn't exist in the playground, to prove that both are correctly bind together.
To do so, run the following commands : 
`yarn playground:build`
`yarn playground:serve`

Then go to http://localhost:9000/test , you should see that the test page was successfully created 🎉

2021-07-13 12:18 UTC, bidoubiwa commented
🔥 A few improvements: 

## 1. Testing command

If both build and serve should be done before testing, you can create a script in `package.json` doing both.

Example: 
`yarn playground:build && yarn playground:serve`
 
After some try out it seems that `yarn playground:dev` generates the same result. See point 4.

## 2. Hot reload

> Bind the playground with the plugin (empty by default). We have to make sure that editing the plugin files refreshes the playground

per #4

When updating the plugin we should be able to trigger the rebuild of the playground and then serve the playground again.
Using for example the command of point 1.

Alternatively, hot reload, if `playground:dev` does the same as `playground:build && playground:serve` can be used for hot reloading. 

## 3. Contributing.md

Testing should be added to `### Tests and Linter <!-- omit in toc -->` in `CONTRIBUTING.md`

## 4. Mandatory Build

It seems following your example that building the playground is mandatory to generate the pages.  I tried using `yarn playground:dev` and `yarn playground:build` was not mandatory to create the pages. Is there a reason why you chose to do both instead of dev?

## 5. Issue linking

Which issue does this PR closes?

2021-07-13 12:18 UTC, bidoubiwa requested changes
🔥 A few improvements: 

## 1. Testing command

If both build and serve should be done before testing, you can create a script in `package.json` doing both.

Example: 
`yarn playground:build && yarn playground:serve`
 
After some try out it seems that `yarn playground:dev` generates the same result. See point 4.

## 2. Hot reload

> Bind the playground with the plugin (empty by default). We have to make sure that editing the plugin files refreshes the playground

per #4

When updating the plugin we should be able to trigger the rebuild of the playground and then serve the playground again.
Using for example the command of point 1.

Alternatively, hot reload, if `playground:dev` does the same as `playground:build && playground:serve` can be used for hot reloading. 

## 3. Contributing.md

Testing should be added to `### Tests and Linter <!-- omit in toc -->` in `CONTRIBUTING.md`

## 4. Mandatory Build

It seems following your example that building the playground is mandatory to generate the pages.  I tried using `yarn playground:dev` and `yarn playground:build` was not mandatory to create the pages. Is there a reason why you chose to do both instead of dev?

## 5. Issue linking

Which issue does this PR closes?

2021-07-13 15:08 UTC, mdubus commented
> ## 4. Mandatory Build
> It seems following your example that building the playground is mandatory to generate the pages. I tried using `yarn playground:dev` and `yarn playground:build` was not mandatory to create the pages. Is there a reason why you chose to do both instead of dev?

You're right, I could have explained how to test it only with the `dev` command instead of the `build + serve`. 
I did so, because this plugin is going to be used on build only. But you're right, it isn't the more convenient way to test for now, therefore I edited the description of this PR in consequence. 
Thanks a lot for your always so constructive feedbacks ! ❤️

2021-07-13 15:37 UTC, bidoubiwa requested changes

2021-07-13 15:37 UTC, bidoubiwa commented on playground/package.json
> +    "restart": "kill-port --port 8000 && yarn start",
```suggestion
    "restart": "kill-port --port 8000 && yarn develop",
```

2021-07-13 15:37 UTC, bidoubiwa commented on playground/package.json
> +    "start": "gatsby develop --open",
```suggestion
    "start": "gatsby develop",
```

Could be used for cypress and thus `open` should not be added.

2021-07-13 15:37 UTC, bidoubiwa commented on package.json
> +    "playground:dev": "yarn --cwd ./playground && yarn --cwd ./playground watch",
```suggestion
    "playground:dev": "yarn --cwd ./playground && yarn --cwd ./playground watch",
    "playground:start": "yarn --cwd ./playground && yarn --cwd ./playground start",
```

2021-07-15 08:43 UTC, bidoubiwa approved these changes
LGTM 🔥

2021-07-15 09:17 UTC, mdubus commented
bors merge

2021-07-15 09:18 UTC, merged