Add cypress
meilisearch/gatsby-plugin-meilisearch pull request #22
Opened 2021-07-15 14:48 UTC by mdubus

2021-07-19 15:18 UTC, bidoubiwa requested changes
🔥🔥🔥 Nice PR

We should be sure that 

`"test:watch": "concurrently --kill-others -s first \"yarn playground:dev\" \"cypress open\""` also triggers the build. See #23 suggested changes.

2021-07-19 15:18 UTC, bidoubiwa commented on package.json
> +    "cy:install": "node ./node_modules/cypress/bin/cypress install",
```suggestion
```

Should be removed, by bad, will be removed in strapi as well.

2021-07-19 15:18 UTC, bidoubiwa commented on .github/workflows/tests.yml
> +        run: yarn
cache can be added to avoid downloading packages at every CI run. example here: https://github.com/meilisearch/strapi-plugin-meilisearch/blob/main/.github/workflows/tests.yml

2021-07-19 15:18 UTC, bidoubiwa commented on CONTRIBUTING.md
>  # Linter
Section explaining how to use `cy:open` and `cy:run` see: https://github.com/meilisearch/strapi-plugin-meilisearch/blob/main/CONTRIBUTING.md

2021-07-20 07:33 UTC, mdubus commented on .github/workflows/tests.yml
> +          node-version: '12.x'
Because it installs the dependencies, and Cypress is incompatible with node 10. 
Got this error: 
`error cypress@7.7.0: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.24.1"`

See here: 
https://github.com/meilisearch/gatsby-plugin-meilisearch/runs/3077825574

2021-07-20 08:04 UTC, bidoubiwa commented on .github/workflows/tests.yml
> +          node-version: '12.x'
You added node `12.x` in both cypress tests and `linter_check`. The linter check does not use cypress, so you shouln't have to add `12.x` in both jobs

2021-07-20 08:24 UTC, mdubus commented on .github/workflows/tests.yml
> +          node-version: '12.x'
As the `linter_check` installs the dependencies (and therefore Cypress), I have to specify the version `12.x` because Cypress is incompatible with the version `10` installed by default

2021-07-20 10:14 UTC, bidoubiwa requested changes

2021-07-20 10:14 UTC, bidoubiwa commented on package.json
> +    "playground:dev": "yarn --cwd ./playground && yarn --cwd ./playground develop",
Should this not be './playground watch' ?

2021-07-20 10:21 UTC, mdubus commented on package.json
> +    "playground:dev": "yarn --cwd ./playground && yarn --cwd ./playground develop",
As we only want to **rebuild** the server on change, this makes no sense to add watch on `playground:dev`. 
I preferred to separate the `development mode` from the `build mode`. 
If I mix both, it's only going to create confusion. What do you think ?

2021-07-20 12:27 UTC, bidoubiwa requested changes
Unfortunately `yarn test` does not work anymore.

2021-07-20 12:27 UTC, bidoubiwa commented on package.json
> +    "playground:dev": "yarn --cwd ./playground && yarn --cwd ./playground develop",
I think the following commands will mostly never be used, and if they are needed users can go to the `playground` folder. Whereas keeping them makes the package.json unnecessarily big: 

```
    "playground:serve": "yarn --cwd ./playground && yarn --cwd ./playground serve",
    "playground:dev": "yarn --cwd ./playground && yarn --cwd ./playground develop",
```

the only two that makes sense when developing this plugin is:
```
"playground:watch:build": "yarn --cwd ./playground && yarn --cwd ./playground watch",
"playground:build": "yarn --cwd ./playground && yarn --cwd ./playground build",
```

`dev` is used to talk about a `development` environment. If your environment needs a rebuild to be useful during development, it should be added. 
Reloading the gatsby server without build has no purpose in developing the plugin.

Thus I would remove the other, change this to this naming:

```
"playground:dev": "yarn --cwd ./playground && yarn --cwd ./playground watch",
"playground:build": "yarn --cwd ./playground && yarn --cwd ./playground build",
"test:watch": "concurrently --kill-others -s first \"yarn playground:dev\" \"cypress open\""
```

2021-07-20 12:46 UTC, bidoubiwa requested changes
`yarn test` should be kept but made usable

2021-07-20 12:46 UTC, bidoubiwa commented on package.json
> +    "test:watch": "concurrently --kill-others -s first \"yarn playground:dev\" \"cypress open\""
`yarn test` is still usefull to run the tests in headless mode

2021-07-20 13:09 UTC, bidoubiwa approved these changes
LGTM 🔥🔥🔥🔥

2021-07-20 13:11 UTC, mdubus commented
bors merge

2021-07-20 13:12 UTC, merged