Get graphql query result
meilisearch/gatsby-plugin-meilisearch pull request #23
Opened 2021-07-19 12:23 UTC by mdubus

Closes #6 

## What's inside this PR ? 

- Removal of the `createPages` example
- Addition of the `pluginOptionsSchema` function, to define the schema of the options passed to the plugin. Note that some of the options have the `any` type, because removing these options from the schema creates a warning on build. I decided to let them in the `pluginOptionsSchema`, but let MeiliSearch handle these errors as they might be more explicit.
- Addition of the `onPostBuild` function with the graphql query inside + log of the result.
- Removal of the `--open` for develop mode, as it switches me to the website tab on every change inside the plugin

## How to test

`yarn && yarn playground:build`

## Screenshots

![Capture d’écran 2021-07-19 à 14 21 36](https://user-images.githubusercontent.com/30866152/126159110-29a578ce-04be-4018-9bc9-c6ddad619d10.png)

2021-07-19 14:24 UTC, bidoubiwa requested changes
🔥
For the moment the `playground:dev` does not rebuild on changes. It is only restarting the server which is not triggering the `onBuild` from gatsby plugin.

In order to do so you should change `restart` in `playground/package.json` to be triggered en build and maybe on develop also if you want to

Also to enable rebuild on your other files and not only on `gatsby-node.js` you should add the triggering of these paths. 
For example: 
`./src` `playground/gatsby-config.js` `playground/package.json`

You can also avoid unnecessary logs in your terminal by using the quiet mode. 

All information to do so can be found [in this readme.md](https://github.com/M-Zuber/npm-watch)

2021-07-19 14:39 UTC, bidoubiwa reviewed
I tried not adding `host` in the plugin config. It makes the build crash. 
As previously discussed after trying with the algolia and typesense plugin, we should never make the build of gatsby crash. 
We should catch the error, log it, but let the build continue. 

Maybe there is an option in `pluginOptionsSchema` that avoids crashing, if not, we should use what [typesense plugin](https://github.com/typesense/gatsby-plugin-typesense) uses as methods.

2021-07-20 10:26 UTC, mdubus commented
> I tried not adding `host` in the plugin config. It makes the build crash.
> As previously discussed after trying with the algolia and typesense plugin, we should never make the build of gatsby crash.
> We should catch the error, log it, but let the build continue.
> 
> Maybe there is an option in `pluginOptionsSchema` that avoids crashing, if not, we should use what [typesense plugin](https://github.com/typesense/gatsby-plugin-typesense) uses as methods.

Okay, I tried to try/catch the errors thrown by `Joi`, but it seems that the crash comes from the function `pluginOptionsSchema` itself. I'm going to remove this function, and will add a custom function to test the options schema. 
Thanks for pointing this out ! 🙏

2021-07-20 14:20 UTC, mdubus commented
> 🔥
> For the moment the `playground:dev` does not rebuild on changes. It is only restarting the server which is not triggering the `onBuild` from gatsby plugin.
> 
> In order to do so you should change `restart` in `playground/package.json` to be triggered en build and maybe on develop also if you want to
> 
> Also to enable rebuild on your other files and not only on `gatsby-node.js` you should add the triggering of these paths.
> For example:
> `./src` `playground/gatsby-config.js` `playground/package.json`
> 
> You can also avoid unnecessary logs in your terminal by using the quiet mode.
> 
> All information to do so can be found [in this readme.md](https://github.com/M-Zuber/npm-watch)

Done with #22

2021-07-20 15:17 UTC, bidoubiwa requested changes
## What throws an error

```js
 if (!config.indexes || !config.indexes.query) {
    throw new Error(`gatsby-plugin-meilisearch: option "indexes.query" missing`)
  }
```
This means we throw when 

1. `indexes` is not present in the settings. 

I don't think `indexes` should be mandatory. It might be just a pre-configuration without any requests yet. Maybe a `warning` but I wouldn't throw on that. 

2. `query` is not present in the `indexes` key

If we check `query` we should check `indexUid` ! 

## How to throw the error

Instead of using the throw API we should use the provided API from gatbsy. See [Typesense](https://github.com/typesense/gatsby-plugin-typesense/blob/master/gatsby-node.js) example.

[The documentation of the reporter API may be useful](https://www.gatsbyjs.com/docs/reference/config-files/node-api-helpers/#reporter)

## How to syntax the error

Based on [Typesense](https://github.com/typesense/gatsby-plugin-typesense/blob/master/gatsby-node.js) plugin, using `[MeiliSearch]` in front of the message is more efficient and more visible. Adding `gatsby plugin` is redundant based on the gatsby context in which we are. 

## Error message

The error message should be more verbose. See typesense plugin example. 

example: 

```js
   const errorMsg = `[Typesense] Field "${attributeName}" is not defined in the collection schema`
```

2021-07-21 07:25 UTC, mdubus commented
> ## How to throw the error
> Instead of using the throw API we should use the provided API from gatbsy. See [Typesense](https://github.com/typesense/gatsby-plugin-typesense/blob/master/gatsby-node.js) example.
> 
> [The documentation of the reporter API may be useful](https://www.gatsbyjs.com/docs/reference/config-files/node-api-helpers/#reporter)

The Gatsby reporter is used inside the `onPostBuild` function, to log the error that is thrown inside the `validatePluginOptions`. If I don't throw, the `onPostBuild` just continues even if there is an error. 

Typesense uses the `reporter.panic` function which stops the build. As it is not what we want, I had to find an alternative :)

2021-07-21 07:30 UTC, mdubus commented
> ## How to syntax the error
> Based on [Typesense](https://github.com/typesense/gatsby-plugin-typesense/blob/master/gatsby-node.js) plugin, using `MeiliSearch:` in front of the message is more efficient and more visible. Adding `gatsby plugin` is redundant based on the gatsby context in which we are.
> 
> This is opinionated! Tell me if you disagree. Maybe other gatsby plugins could help us decide.

Not sure about this. What if users are also going to use MeiliSearch in front-end, as we do with Instant MeiliSearch in the playground ? Isn't it going to be confusing ?

2021-07-21 08:23 UTC, bidoubiwa commented
> The Gatsby reporter is used inside the onPostBuild function, to log the error that is thrown inside the validatePluginOptions. If I don't throw, the onPostBuild just continues even if there is an error.

Absolutely, that's to bad. Can we remove the `new Error` part to just have the error message without the whole stack?

> Not sure about this. What if users are also going to use MeiliSearch in front-end, as we do with Instant MeiliSearch in the playground ? Isn't it going to be confusing ?

It is very subjective. I'm not sure there will be another meilisearch task running during the gatsby build so I don't see a reason why there would be another `meilisearch` reporter in the terminal on build. 
Plus typesense is used in front-end as well.
But either case it is subjective so keep the one you, like all are good :)

2021-07-21 12:08 UTC, bidoubiwa requested changes
🔥 Thanks for the changes

2021-07-21 12:08 UTC, bidoubiwa commented on gatsby-node.js
> +}
Errors can be simplified like this if you are only going to use `error.message`

```js
throw getValidationError('indexes.indexUid')
```

You can also be a bit more verbose

```js
throw getValidationError('query in the indexes object')
```

2021-07-21 12:08 UTC, bidoubiwa commented on gatsby-node.js
> +  `[${PLUGIN_NAME}] Field "${field}" is not defined in the collection schema`
```suggestion
  `[${PLUGIN_NAME}] The Field "${field}" is required in the plugin configuration`
```

This text `in the collection schema` is related to typesense inner working. 
In our case it should be something like `in the plugin configuration`.

Maybe `present` is not the right word..

2021-07-21 12:44 UTC, bidoubiwa requested changes
In a previous comment we talked about`indexes` itself should not be mandatory, with these conditions `indexes` is mandatory.

> I don't think indexes should be mandatory. It might be just a pre-configuration without any requests yet. Maybe a warning but I wouldn't throw on that.

See this code in [algolia's plugin](https://github.com/algolia/gatsby-plugin-algolia/blob/bc3094bb829740b094bfeb96be81b7f84e619a7b/gatsby-node.js#L78) in algolia. 

```js
groupQueriesByIndex(queries = [], config)
```
They are empty by default. 
queries is equivalent to `indexes` in our code. 

Also in [typesense plugin](https://github.com/typesense/gatsby-plugin-typesense/blob/587ee06b762620a850450a88e9506b5ebe6f0a35/gatsby-node.js#L37)
it is not mandatory. 

Dev should be able to prepare configuration without having to add indexes.

2021-07-21 12:44 UTC, bidoubiwa commented on gatsby-node.js
> +  `[${PLUGIN_NAME}] The Field ${field} is required in the plugin configuration`
```suggestion
  `[${PLUGIN_NAME}] The field ${field} is required in the plugin configuration`
```

woops

2021-07-21 15:22 UTC, bidoubiwa requested changes
Small small small change and then 🚀🚀🚀

2021-07-21 15:22 UTC, bidoubiwa commented on gatsby-node.js
> +  }
```suggestion
  if (!queries.indexUid) {
    throw getValidationError('"indexUid" in the "queries" object')
  }
  if (!queries.query) {
    throw getValidationError('"query" in the "queries" object')
  }
```

just ordering by importance

2021-07-21 16:37 UTC, bidoubiwa commented on gatsby-node.js
>      throw getValidationError('"indexUid" in the "queries" object')
```suggestion
    throw getValidationError('"indexUid" in the "indexUid" object')
```

2021-07-21 16:38 UTC, bidoubiwa approved these changes
LGTM 🔥🔥

2021-07-21 16:39 UTC, mdubus commented
bors merge

2021-07-21 16:39 UTC, merged