Test document indexation
meilisearch/gatsby-plugin-meilisearch pull request #26
Opened 2021-07-27 07:19 UTC by mdubus

2021-08-19 12:17 UTC, bidoubiwa requested changes
### Files should keep the same naming convention: 
ex: `indexToMeiliSearch.test.js` -> `index-to-meilisearch.test.js`
ex `article_page.spec.js` -> `article-page.spec.js`

### test redundancy

when doing 

```js
  expect(() => validate()).toThrow()
  expect(() => validate()).toThrow("...")
```

These might be redundant as they do the same thing but one time more precisely than the other.

2021-08-19 12:17 UTC, bidoubiwa commented on CONTRIBUTING.md
> +#### End-to-End tests
End to end tests,integrations tests and linting should not be separated into two categories. It avoid having a contributing guide that is overwhelming. 


They can be added in the same code sample: 

```bash
# Run a MeiliSearch instance
docker pull getmeili/meilisearch:latest # Fetch the latest version of MeiliSearch image from Docker Hub
docker run -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --master-key=masterKey --no-analytics=true

# Tests the project
yarn test # integration tests
yarn test:e2e # end to end tests

# Tests the project in watch/open mode
yarn test:watch
yarn test:e2e:watch

# Linter
yarn lint
# Linter with fixing
yarn lint:fix
```

2021-08-19 12:17 UTC, bidoubiwa commented on CONTRIBUTING.md
> +```
Environment variables for testing should have a default value a bit like on the other SDK's (example)[https://github.com/meilisearch/meilisearch-js/blob/main/tests/meilisearch-test-utils.ts].

You can provide the file name where the user can change these variables if he'd like to but it is not necessary per se.

2021-08-19 12:17 UTC, bidoubiwa commented on package.json
> +    "react": "^17.0.2",
is `react` needed in the root dir?

2021-08-19 12:22 UTC, bidoubiwa commented on CONTRIBUTING.md
> +```
this did not work for me :( but see main comment of review

2021-08-23 08:47 UTC, mdubus commented on CONTRIBUTING.md
> +```
Just added a fallback in the `fakeConfig` (`tests/utils.js` file) as I prefer not to push a `.env` file 🙂

2021-08-23 08:49 UTC, mdubus commented on package.json
> +    "react": "^17.0.2",
Nope, you're right. Just removed it from the dependencies. 
The only inconvenience is that I now have this message on `yarn lint`:
```
Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.
```

Do you want me to add a `.eslintrc` into the `playground` folder with all the react plugin & configurations for eslint (and remove them from the root), or do you want to leave it like this ?

2021-08-23 08:50 UTC, mdubus commented on CONTRIBUTING.md
> +```
Should work now. I added the `playground:start` concurrently 😉

2021-08-23 08:51 UTC, mdubus commented
> ### Files should keep the same naming convention:
> ex: `indexToMeiliSearch.test.js` -> `index-to-meilisearch.test.js`
> ex `article_page.spec.js` -> `article-page.spec.js`

Done

> 
> ### Test redundancy
> when doing
> 
> ```js
>   expect(() => validate()).toThrow()
>   expect(() => validate()).toThrow("...")
> ```
> 
> These might be redundant as they do the same thing but one time more precisely than the other.
> 

Done

> ### Integration tests
> `yarn test` is not possible without running the gatsby playground. This command should be runable without any further configuration. I think we should either mock the answer of graphQL or consider launching the playground concurrently when running `yarn test`.

I added the playground concurrently 👍

2021-08-28 14:58 UTC, bidoubiwa requested changes
Very small changes and we r good to go 🔥🔥

2021-08-28 14:58 UTC, bidoubiwa commented on tests/index-to-meilisearch.test.js
> +describe('index to MeiliSearch', () => {
```suggestion
describe('Index to MeiliSearch', () => {
```

2021-08-28 14:58 UTC, bidoubiwa commented on CONTRIBUTING.md
> +
```suggestion
```

2021-08-30 13:10 UTC, bidoubiwa approved these changes
LGTM 🔥

2021-08-30 13:40 UTC, mdubus commented
bors merge

2021-08-30 13:42 UTC, merged