Add more explanation on readme about how it works
meilisearch/gatsby-plugin-meilisearch pull request #91
Opened 2021-12-13 14:16 UTC by mdubus

2021-12-13 14:45 UTC, bidoubiwa requested changes
By taking inspiration from https://github.com/meilisearch/docs-searchbar.js you can what is expected from a getting started and also where you should add the explanation about the repository.

2021-12-13 14:45 UTC, bidoubiwa commented on README.md
> +This plugin makes it possible for you to get the content of your Gatsby website, and index it to MeiliSearch.
```suggestion
With this plugin, you can index/add the data used in your [Gatsby application](https://www.gatsbyjs.com/docs/content-and-data/) into MeiliSearch. 

For example, using the same queries you are using to fetch and use data from the  [`mdx-plugin`](https://www.gatsbyjs.com/docs/how-to/routing/mdx-plugins/), the data can also be indexed in MeiliSearch (see query example below).
```

2021-12-13 14:45 UTC, bidoubiwa commented on README.md
> +This plugin is not a scrapper, and therefore you will need to tell it which content it has to retrieve. This is made possible thanks to GraphQL and the queries you'll provide in your `gatsby-config.j
```suggestion
The plugin is not a scrapper, and therefore you need to specify which content should be indexed. You are able to do so with the GraphQL queries you provide in your `gatsby-config.js` file. The queries are used against the GraphQL API your Gatbsy app provides. 

To learn more about Gatsby and GraphQL queries, you can [discover how it works](https://www.gatsbyjs.com/docs/conceptual/graphql-concepts/).
```

2021-12-13 14:45 UTC, bidoubiwa commented on README.md
> +Once the content has been retrieved, it is send to your MeiliSearch instance for indexation.
```suggestion
During the build of your Gatsby application, the data is fetched from Gatsby and then, it is indexed in your MeiliSearch instance.
```

2021-12-13 14:45 UTC, bidoubiwa commented on README.md
> +## 🎬 Getting started
The getting started should be a step by step process to help the user use the plugin. Explainations should be add the top of the readme. See `https://github.com/meilisearch/docs-searchbar.js` as an example.

2021-12-13 14:45 UTC, bidoubiwa commented on README.md
> +- [instant-meilisearch](https://github.com/meilisearch/instant-meilisearch): a UI library that lets you quickly build a search interface in your front-end application
Not sure this should be kept in the getting started.

2021-12-14 12:14 UTC, bidoubiwa requested changes

2021-12-14 12:14 UTC, bidoubiwa commented on README.md
> +**Add your documents to MeiliSearch**
This should be called `Build your project` as a step of the getting started

2021-12-14 12:14 UTC, bidoubiwa commented on README.md
> +  ],
This should be added step by step

- Add credentials
```
plugins: [
    {
      resolve: 'gatsby-plugin-meilisearch,
      options: {
        host: 'http://localhost:7700',
        apiKey: "masterkey"
        },
      },
    },
```

- Add a query in `indexes`

Here you add a story line where you use  Use the `md` plugin to create a scenario to follow as your query example does not help if the user did not install the md plugin. 

Also explain what `transformer` does in this context

2021-12-14 12:14 UTC, bidoubiwa commented on README.md
> +If you go to http://0.0.0.0:7700/, you should see our [mini-dashboard](https://github.com/meilisearch/mini-dashboard/) without any index nor documents inside. So let's fill it !
This should be before the getting started in the `installation` part. 

See [strapi plugin](https://github.com/meilisearch/strapi-plugin-meilisearch/#-installation) or [docs-searchbar](https://github.com/meilisearch/docs-searchbar.js/)

2021-12-14 12:14 UTC, bidoubiwa commented on README.md
> +- [instant-meilisearch](https://github.com/meilisearch/instant-meilisearch): a UI library that lets you quickly build a search interface in your front-end application
This can be a section called  `Integrate search components`

2021-12-14 12:14 UTC, bidoubiwa commented on README.md
> +The `gatsby-plugin-meilisearch` fetches and sends your documents for indexation to MeiliSearch on build, thanks to your graphQL queries. You can try it by triggering a build of your website:
```suggestion
The `gatsby-plugin-meilisearch` fetches and sends your documents for indexation to MeiliSearch on build, using the graphQL queries provided in the `gatsby-config.js` file. 

Build your project:

2021-12-14 12:14 UTC, bidoubiwa commented on README.md
> +`yarn build` or `npm run build`
Lets assume the user do not have these script name an call them `gatsby build`. Also by convention they should be in triple quotes 

```
gatsby build
```

2021-12-14 12:14 UTC, bidoubiwa commented on README.md
> +The build should succeed, and you should see an information telling you that your content was successfully indexed: `success gatsby-plugin-meilisearch - x.xxxs - Documents added to MeiliSearch`
```suggestion
After the build, a message in your terminal should confirm that your that your content was successfully indexed: 
`success gatsby-plugin-meilisearch - x.xxxs - Documents added to MeiliSearch`
```

I can not suggest it here but here as well, you should add triple quotes. Single quotes are used to emphasis some technical keywords

2021-12-14 12:14 UTC, bidoubiwa commented on README.md
> +- `http://localhost:8000/___graphql` where you can discover and build graphQL queries
This all should be added in `installation` after `run a meilisearch`

2021-12-14 12:14 UTC, bidoubiwa commented on README.md
> +Follow the steps, then go to the newly created repository and start Gastby:
This part should not be documented by us. You can make a link to the documentation of the install of gatsby. Here we will only say 

> Run your Gatsby app, you should have access to: 
> - `http..`
> 
> If you don't have a Gatsby app yet, please refer to the [Gatsby documentation](#link)


Please improve my suggestion

2021-12-14 12:14 UTC, bidoubiwa commented on README.md
> +`yarn add gatsby-plugin-meilisearch` or `npm install gatsby-plugin-meilisearch`
Commands should be added in triple quotes by convention. Refer to the other SDK's for examples

2021-12-14 12:14 UTC, bidoubiwa commented on README.md
> +  ],
Also, we only need the `plugin` field. Not the whole config file

2021-12-14 12:19 UTC, bidoubiwa requested changes

2021-12-14 12:19 UTC, bidoubiwa commented on README.md
> +
Here you should add a context. For example

```
In the gatsby-config.js file, the MeiliSearch plugin accepts the following parameters:
```

2021-12-14 12:19 UTC, bidoubiwa commented on README.md
> +},
It is an example of which part of the configurations? It should already be running. 
Not sure why it is added before the next parameters.

Also, no need to repeat how to run a MeiliSearch.

2021-12-15 12:03 UTC, bidoubiwa requested changes

2021-12-16 08:04 UTC, mdubus commented
I commited your changes for better wording, but I disagree with one point. You changed the `indexUid` to `page_content` but it's not true, because we actually retrieve page information (url of the pages, chunk names, ...) but not the content itself of the pages. 
I thought changes it to `page_information`, WDYT @bidoubiwa  ?

2021-12-16 12:32 UTC, bidoubiwa commented
`page_information` is great!

2022-01-13 10:58 UTC, shivaylamba requested changes
A couple of typo's in the gatsby-config.js

2022-01-13 10:58 UTC, shivaylamba commented on README.md
> +    resolve: 'gatsby-plugin-meilisearch,
Missing ``` ' ``` in ```resolve: 'gatsby-plugin-meilisearch```

2022-01-13 10:58 UTC, shivaylamba commented on README.md
> +          indexUid: 'pages_url'
Missing ``` , ``` after ``` indexUid: 'pages_url' ```

2022-01-13 12:52 UTC, mdubus commented
> A couple of typo's in the gatsby-config.js

Fixed, thanks a lot @shivaylamba ! 🙏

2022-01-25 12:12 UTC, bidoubiwa requested changes

2022-01-25 17:18 UTC, bidoubiwa commented
bors try

2022-01-25 17:31 UTC, bidoubiwa approved these changes
bors merge

2022-01-25 17:37 UTC, merged