[WIP] Update for v0.25
meilisearch/gatsby-plugin-meilisearch pull request #99
Opened 2022-01-13 13:07 UTC by mdubus

2022-01-13 18:22 UTC, curquiza commented
When you are doing a WIP, open directly a draft PR, or convert your already existing PR as a draft :) 

<img width="361" alt="Capture d’écran 2022-01-13 à 19 22 03" src="https://user-images.githubusercontent.com/20380692/149387321-ac52549f-a120-438e-a2bb-c7e75c25ed8c.png">

2022-01-18 07:40 UTC, mdubus commented
> When you are doing a WIP, open directly a draft PR, or convert your already existing PR as a draft 🙂 No need to put WIP in the name of the PR See our contributing guidelines: https://github.com/meilisearch/gatsby-plugin-meilisearch/blob/main/CONTRIBUTING.md#github-pull-requests-
> 
> <img alt="Capture d’écran 2022-01-13 à 19 22 03" width="361" src="https://user-images.githubusercontent.com/20380692/149387321-ac52549f-a120-438e-a2bb-c7e75c25ed8c.png">

Thanks a lot !
Since I was in a rush I totally forgot this option 🙈
Just did it now, thanks again ! 🙏

2022-01-25 15:53 UTC, bidoubiwa requested changes
🔥

2022-01-25 15:53 UTC, bidoubiwa commented on gatsby-node.js
> +        if (index) await index.delete()
```suggestion
        await index.delete()
```

Index will always exists as it does not make any http call. If the index does not exists the `task` in MeiliSearch will fail but it does not impact the following tasks.

2022-01-25 15:59 UTC, bidoubiwa commented
bors merge

2022-01-25 16:57 UTC, bidoubiwa approved these changes
LGTM

2022-01-25 17:13 UTC, bidoubiwa commented
bors merge

2022-01-25 17:16 UTC, merged